import { Difficulty, Exercise, MuscleGroup, Settings } from './types';

export const DEFAULT_SETTINGS: Settings = {
  exerciseDuration: 30,
  exercisesPerCycle: 10,
  cycleCount: 2,
  ttsVoiceURI: null,
};

export const SEED_EXERCISES: Exercise[] = [
  // НОГИ (LEGS)
  { id: '1', name: 'Jump Squat', description: 'Взрывное приседание с максимальным прыжком вверх.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.HARD },
  { id: '2', name: 'Bulgarian Split Squat', description: 'Выпады с одной ногой на стуле.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '3', name: 'Pistol Squat', description: 'Приседание на одной ноге, вторая вытянута вперед.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.HARD },
  { id: '4', name: 'Lateral Lunge', description: 'Широкий шаг в сторону с глубоким приседом на одну ногу.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '5', name: 'Step Up', description: 'Поочередный подъем на стул с акцентом на пятку.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '6', name: 'Single Leg Glute Bridge', description: 'Подъем таза лежа, одна нога поднята вертикально.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '7', name: 'High Knees', description: 'Бег на месте с максимальным подниманием колен к груди в быстром темпе.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '8', name: 'Jumping Plie Squat', description: 'Приседания с широкой постановкой стоп и прыжком.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '9', name: 'Jumping Lunge', description: 'Взрывные прыжки с переменой ног в воздухе.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.HARD },
  { id: '10', name: 'Single Leg Calf Raise', description: 'Проработка икроножных мышц стоя на одной ноге.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '11', name: 'Wall Sit', description: 'Статическое удержание полуприседа прижавшись к стене.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '12', name: 'Diagonal Lunge', description: 'Выпад назад по диагонали (реверанс).', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '61', name: 'Jumping Jack', description: 'Кардио-упражнение: прыжки с одновременным разведением рук и ног в стороны.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '62', name: 'Lateral Drop And Touch', description: 'Прыжок в сторону с последующим приседанием и касанием пола противоположной рукой.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '63', name: 'Drop And Touch', description: 'Прыжок на месте с приземлением в присед и касанием пола рукой.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '64', name: 'Skater', description: 'Прыжки из стороны в сторону, имитирующие движения конькобежца.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '65', name: 'Lunge Touch And Kick', description: 'Выпад вперед с касанием пола рукой, затем подъем и удар ногой вперед.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '66', name: 'Plyo Split Squat', description: 'Взрывной сплит-присед с прыжком и сменой ног в воздухе.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.HARD },
  { id: '67', name: 'Side To Side Hops', description: 'Быстрые прыжки из стороны в сторону, удерживая ноги вместе.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '68', name: 'Lunge And Rotation', description: 'Выпад вперед с одновременным поворотом корпуса в сторону передней ноги.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },
  { id: '69', name: 'One Leg Power Squat', description: 'Приседание на одной ноге с последующим взрывным подъемом вверх.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.HARD },
  { id: '70', name: 'One Leg Squat Hops', description: 'Приседание на одной ноге с последующими небольшими прыжками вверх.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.HARD },
  { id: '71', name: 'One Leg Squat Touch', description: 'Приседание на одной ноге с касанием пола противоположной рукой.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.HARD },
  { id: '72', name: 'One Leg Wall Sit', description: 'Статическое удержание полуприседа у стены на одной ноге.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.HARD },
  { id: '73', name: 'Power Squat', description: 'Глубокий присед с акцентом на взрывной подъем вверх.', muscleGroup: MuscleGroup.LEGS, difficulty: Difficulty.MEDIUM },

  // РУКИ (ARMS)
  { id: '13', name: 'Chair Dip', description: 'Классическое упражнение на трицепс с опорой сзади.', muscleGroup: MuscleGroup.ARMS, difficulty: Difficulty.MEDIUM },
  { id: '14', name: 'Diamond Push-Up', description: 'Отжимания с узкой постановкой рук (пальцы образуют ромб).', muscleGroup: MuscleGroup.ARMS, difficulty: Difficulty.HARD },
  { id: '15', name: 'Plank To Elbow', description: 'Смена положения из планки на прямых руках в планку на локтях.', muscleGroup: MuscleGroup.ARMS, difficulty: Difficulty.MEDIUM },
  { id: '16', name: 'Shadow Boxing', description: 'Интенсивные удары перед собой в высоком темпе.', muscleGroup: MuscleGroup.ARMS, difficulty: Difficulty.MEDIUM },
  { id: '17', name: 'Triceps Push-Up', description: 'Локти прижаты к корпусу и смотрят строго назад.', muscleGroup: MuscleGroup.ARMS, difficulty: Difficulty.MEDIUM },
  { id: '18', name: 'Plank Walk', description: 'Перемещение в сторону в положении упор лежа.', muscleGroup: MuscleGroup.ARMS, difficulty: Difficulty.MEDIUM },
  { id: '19', name: 'Wall Curl', description: 'Имитация подъема штанги за счет давления рук на стену.', muscleGroup: MuscleGroup.ARMS, difficulty: Difficulty.MEDIUM },
  { id: '20', name: 'Plank Up', description: 'Из положения стоя наклон и «шаги» руками до упора лежа.', muscleGroup: MuscleGroup.ARMS, difficulty: Difficulty.MEDIUM },
  { id: '21', name: 'One Arm Push-Up', description: 'Экстремальная нагрузка на трицепс и плечевой пояс.', muscleGroup: MuscleGroup.ARMS, difficulty: Difficulty.HARD },
  { id: '22', name: 'Push-Up Hold', description: 'Зависание в нижней точке отжиманий на время.', muscleGroup: MuscleGroup.ARMS, difficulty: Difficulty.HARD },
  { id: '23', name: 'Arm Circles', description: 'Изолирующая нагрузка на дельты в статико-динамике.', muscleGroup: MuscleGroup.ARMS, difficulty: Difficulty.MEDIUM },
  { id: '24', name: 'Plank Fist Raise', description: 'Переход с ладоней на кулаки для укрепления кистей и рук.', muscleGroup: MuscleGroup.ARMS, difficulty: Difficulty.HARD },

  // ПРЕСС (ABS)
  { id: '25', name: 'Bicycle Crunch', description: 'Поочередное касание локтем противоположного колена лежа.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '26', name: 'V-Up', description: 'Одновременный подъем корпуса и прямых ног.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.HARD },
  { id: '27', name: 'Mountain Climber', description: 'Подтягивание колен к груди в упоре лежа в быстром темпе.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '28', name: 'Russian Twist', description: 'Повороты корпуса сидя с оторванными от пола ногами.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '29', name: 'Reverse Crunch', description: 'Подъем таза вверх за счет мышц пресса лежа на спине.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '30', name: 'Star Plank', description: 'Планка с максимально широкой постановкой рук и ног.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.HARD },
  { id: '31', name: 'Leg Raise', description: 'Медленное опускание ног без касания пола.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '32', name: 'Side Plank Hip Lift', description: 'Динамическая боковая планка для косых мышц.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '33', name: 'Dead Bug', description: 'Контролируемое опускание разноименных руки и ноги.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '34', name: 'L-Sit', description: 'Удержание прямых ног на весу, опираясь руками на стул.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.HARD },
  { id: '35', name: 'Toe Touch Crunch', description: 'Подъем лопаток к поднятым вертикально ногам.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '36', name: 'Burpee', description: 'Комплексное упражнение с прыжком и упором лежа.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.HARD },
  { id: '79', name: 'Abdominal Crunch', description: 'Классическое упражнение для пресса: подъем верхней части тела из положения лежа.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '80', name: 'Full Side Plank', description: 'Удержание тела в боковой планке на одной руке и ноге.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '81', name: 'Plank', description: 'Статическое упражнение: удержание тела в прямой линии на предплечьях и носках.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '82', name: 'Reverse Crunch And Hug', description: 'Обратное скручивание с подтягиванием колен к груди и обхватом их руками.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '83', name: 'Reverse Plank', description: 'Удержание тела в прямой линии лицом вверх, опираясь на руки и пятки.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '84', name: 'Scissor Kicks', description: 'Лежа на спине, попеременный подъем и опускание прямых ног, имитируя движение ножниц.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '85', name: 'Side Plank', description: 'Удержание тела в боковой планке на предплечье и боковой части стопы.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '86', name: 'Side Plank Crunch', description: 'Боковая планка с подтягиванием верхнего колена к локтю.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },
  { id: '87', name: 'V Sit Twist', description: 'Удержание тела в положении V с поворотами корпуса из стороны в сторону.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.HARD },
  { id: '88', name: 'Windscreen Wipers', description: 'Лежа на спине, подъем ног и их движение из стороны в сторону, имитируя работу дворников.', muscleGroup: MuscleGroup.ABS, difficulty: Difficulty.MEDIUM },

  // ГРУДЬ (CHEST)
  { id: '37', name: 'Wide Push-Up', description: 'Отжимания с постановкой рук значительно шире плеч.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.MEDIUM },
  { id: '40', name: 'Archer Push-Up', description: 'Перенос веса на одну руку во время спуска.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.HARD },
  { id: '38', name: 'Chair Decline Push-Up', description: 'Акцент на верхнюю часть грудных мышц.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.HARD },
  { id: '39', name: 'Power Push-Up', description: 'Отжимания с хлопком или отрывом ладоней от пола.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.HARD },
  { id: '42', name: 'Pause Push-Up', description: 'Классика с задержкой на 3 секунды в нижней точке.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.MEDIUM },
  { id: '43', name: 'Chair Push-Up', description: 'Опора руками на сиденье стула.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.MEDIUM },
  { id: '44', name: 'Slow Negative Push-Up', description: 'Максимальное время под нагрузкой в негативной фазе.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.MEDIUM },
  { id: '45', name: 'Offset Push-Up', description: 'Одна рука впереди, другая сзади, смена через прыжок.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.HARD },
  { id: '41', name: 'Hindu Push-Up', description: 'Волнообразное движение корпусом из «собаки мордой вниз».', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.HARD },
  { id: '46', name: 'Push-Up And Rotation', description: 'Поворот корпуса в боковую планку после каждого отжимания.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.MEDIUM },
  { id: '47', name: 'Chest Press', description: 'Изометрическое сжатие ладоней перед грудью стоя.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.MEDIUM },
  { id: '48', name: 'Spiderman Push-Up', description: 'Подтягивание колена к локтю во время отжимания.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.HARD },
  { id: '74', name: 'Bird Dog Push-Up', description: 'Отжимание с одновременным подъемом противоположной руки и ноги в верхней точке.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.HARD },
  { id: '75', name: 'Chair Pike Push-Up', description: 'Отжимание в положении «пике» с ногами на стуле, акцент на плечи.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.HARD },
  { id: '76', name: 'Grasshopper Push-Up', description: 'Отжимание с приведением колена к противоположному локтю в нижней точке.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.HARD },
  { id: '77', name: 'One Leg Push-Up', description: 'Отжимание с поднятой одной ногой для увеличения сложности.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.HARD },
  { id: '78', name: 'Staggered Push-Up', description: 'Отжимание с одной рукой впереди другой для смещения нагрузки.', muscleGroup: MuscleGroup.CHEST, difficulty: Difficulty.MEDIUM },

  // СПИНА (BACK)
  { id: '49', name: 'Superman', description: 'Одновременный подъем рук и ног лежа на животе.', muscleGroup: MuscleGroup.BACK, difficulty: Difficulty.MEDIUM },
  { id: '50', name: 'Boat Pose', description: 'Удержание позы супермена с динамическим раскачиванием.', muscleGroup: MuscleGroup.BACK, difficulty: Difficulty.MEDIUM },
  { id: '51', name: 'Hyperextension', description: 'Подъем только верхней части корпуса лежа на животе.', muscleGroup: MuscleGroup.BACK, difficulty: Difficulty.MEDIUM },
  { id: '52', name: 'Swimmer', description: 'Поочередные махи разноименными руками и ногами лежа.', muscleGroup: MuscleGroup.BACK, difficulty: Difficulty.MEDIUM },
  { id: '53', name: 'W Raise', description: 'Сведение лопаток лежа, руки образуют букву W.', muscleGroup: MuscleGroup.BACK, difficulty: Difficulty.MEDIUM },
  { id: '54', name: 'Reverse Bridge', description: 'Упор сзади на прямых руках, подъем таза до прямой линии.', muscleGroup: MuscleGroup.BACK, difficulty: Difficulty.MEDIUM },
  { id: '55', name: 'Table Pull-Up', description: 'Горизонтальные подтягивания, используя край стола.', muscleGroup: MuscleGroup.BACK, difficulty: Difficulty.HARD },
  { id: '56', name: 'Snow Angel', description: 'Движение прямыми руками вдоль пола лежа на животе.', muscleGroup: MuscleGroup.BACK, difficulty: Difficulty.MEDIUM },
  { id: '57', name: 'Y Raise', description: 'Подъем рук вперед-вверх в форме буквы Y лежа на животе.', muscleGroup: MuscleGroup.BACK, difficulty: Difficulty.MEDIUM },
  { id: '58', name: 'Bird Dog', description: 'Подъем противоположных руки и ноги из планки.', muscleGroup: MuscleGroup.BACK, difficulty: Difficulty.HARD },
  { id: '59', name: 'Bent Over Fly', description: 'Максимальное сжатие лопаток в наклоне корпуса.', muscleGroup: MuscleGroup.BACK, difficulty: Difficulty.MEDIUM },
  { id: '60', name: 'Back Widow', description: 'Подъем грудной клетки лежа на спине с опорой на локти.', muscleGroup: MuscleGroup.BACK, difficulty: Difficulty.HARD }
];


export const ALL_MUSCLE_GROUPS = [
  MuscleGroup.LEGS,
  MuscleGroup.ABS,
  MuscleGroup.BACK,
  MuscleGroup.CHEST,
  MuscleGroup.ARMS,
  MuscleGroup.SHOULDERS
];